version: '3.8'
services:
  app:
    container_name: phptest_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - br0
    tty: true

  db:
    container_name: phptest_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=no1s
    networks:
      - br0
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - br0
        #node:
        #  image: node:12.13-alpine
        #  tty: true
        #  volumes:
        #    - ./src:/var/www/html
        #  working_dir: /var/www/html
        #  networks:
        #    - br0
networks:
  br0:
    driver: bridge
